# Author: Richard Barrett
# Creation Date: 12/18/2019
# Purpose: INSTALLATION OF CHOCOLATEY PACKAGES
# Organization: DVISD
choco install wget -y
choco install curl -y 
choco install googlechrome -y 
choco install flashplayerplugin -y
choco install flashplayeractivex -y 
choco install nodejs -y
choco install jdk8 -y
choco install filezilla -y
choco install teamviewer -y 
choco install putty -y
choco install keepass -y 
choco install vim -y
choco install sourcetree -y 
choco install python -y
choco install php -y 
choco install ruby -y
choco install awscli -y
choco install azure-cli -y 
choco install virtualbox -y
choco install vagrant -y 
choco install kubernetes-cli -y 
choco install windirstat -y
choco install citrix-receiver -y
choco install slack -y 
choco install postman -y 
choco install sublimetext2 -y
choco install atom -y
choco install puppet -y
choco install microsoft-teams -y
choco install r.project -y
choco install r.studio -y
choco install nmap -y
choco install dellcommandupdate -y 
choco install anaconda3 -y 
choco install lastpass -y 
choco install docker-desktop -y 
choco install androidstudio -y 
choco install mongodb -y
choco install postgresql -y 
choco install rabbitmq -y 
choco install openssh -y
choco install gpg4win -y
